name: run the docker compose
on: [workflow_dispatch]
jobs:
    run-on:
        runs-on: ubuntu-latest
        services:
            app:
                image: shamdouchi/node-app
                ports:
                    - 3001:3000
                env:
                    MONGO_HOSTNAME: mongo
            mongo:
                image: mongo
                ports:
                    - 27017:27017
        steps:
            - name: add a new user
              run: |
                  curl -X POST http://localhost:3001/api/users \
                    -H "Content-Type: application/json" \
                    -d '{"username": "mohamed", "address": "azhar"}'
            - name: show users
              run: curl http://localhost:3001/api/users
